### ISSUE TITLE
ارور هنگام اجرا

### ISSUE THREAD

**Issue by rezakhosh78** [malkemit/namizun#24]
سلام. مشکل رو چه طور حل کنم:

Exception in thread Thread-2 (main_menu):
Traceback (most recent call last):
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 677, in _connect
    raise err
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 665, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
Exception in thread Thread-1 (monitor):y", line 953, in run
Traceback (most recent call last):lf._kwargs)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 611, in connectmeter('in_submenu', False)
    sock = self.retry.call_with_retry(database.py", line 77, in set_parameter
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retryn/venv/lib/python3.10/site-packages/redis/commands/core.p    return do()in set
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>un/venv/lib/python3.10/site-packages/redis/client.py", lin    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 677, in _connectun/venv/lib/python3.10/site-packages/redis/connection.py",    raise errn get_connection
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 665, in _connectun/venv/lib/python3.10/site-packages/redis/connection.py",    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. ConnecDuring handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/namizun/namizun_core/monitor.py", line 71, in monitor
    old_bytes_sent, old_bytes_recv = get_network_io()
  File "/var/www/namizun/namizun_core/monitor.py", line 16, in get_network_io
    return io.bytes_sent + database.get_parameter('total_upload_before_reboot') \
  File "/var/www/namizun/namizun_core/database.py", line 66, in get_parameter
    data = my_db.get(prefix + key)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/commands/core.py", line 1705, in get
    return self.execute_command("GET", name)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 1387, in get_connection
    connection.connect()

**Comment by malkemit** [comment]
سلام


systemctl restart redis

اینو بزنین و بعد تست کنید
