### ISSUE TITLE
ارور بعد از دستور namizun

### ISSUE THREAD

**Issue by reza3723** [malkemit/namizun#47]
سلام تشکر بابت اسکریپت خوب شما 
ولی بعد از زدن دستور namizun به ارور ضمیمه شده مواجه میشم 
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/var/www/namizun/venv/lib/python3.8/site-packages/redis/connection.py", line 1394, in get_connection
    raise ConnectionError("Connection has data")
redis.exceptions.ConnectionError: Connection has data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Exception in thread Thread-1:
Traceback (most recent call last):ng.py", line 870, in run
  File "/var/www/namizun/venv/lib/python3.8/site-packages/redis/connection.py", line 1394, in get_connection
    raise ConnectionError("Connection has data")py", line 18, in menu
redis.exceptions.ConnectionError: Connection has data
  File "/var/www/namizun/namizun_core/database.py", line 83, in set_parameter
During handling of the above exception, another exception occurred:
  File "/var/www/namizun/venv/lib/python3.8/site-packages/redis/commands/core.py", line 2220, in set
Traceback (most recent call last):ET", *pieces, **options)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_innerpy", line 1235, in execute_command
    self.run()f.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python3.8/threading.py", line 870, in runredis/connection.py", line 1399, in get_connection
    self._target(*self._args, **self._kwargs)dy")
  File "/var/www/namizun/namizun_menu/monitor.py", line 59, in system_usage
    old_bytes_sent, old_bytes_recv = network.get_network_io()
  File "/var/www/namizun/namizun_core/network.py", line 18, in get_network_io
    return io.bytes_sent + database.get_parameter('upload_amount_synchronizer') \
  File "/var/www/namizun/namizun_core/database.py", line 72, in get_parameter
    data = my_db.get(prefix + key)
  File "/var/www/namizun/venv/lib/python3.8/site-packages/redis/commands/core.py", line 1705, in get
    return self.execute_command("GET", name)

**Comment by malkemit** [comment]
سلام

systemctl restart redis

اینو بزنین

**Comment by malkemit** [comment]
systemctl status redis

جواب اینو برام بفرستین
