### ISSUE TITLE
بعد از نصب زمانی که دستور namizun  وارد می شود اررور زير نمایش داده می شود

### ISSUE THREAD

**Issue by hatinati2** [malkemit/namizun#90]
Exception in thread Thread-2 (menu):
Traceback (most recent call last):
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 645, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
Exception in thread Thread-1 (system_usage):)
Traceback (most recent call last):enu/main_menu.py", line 18, in menu
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 611, in connect
    sock = self.retry.call_with_retry(database.py", line 83, in set_parameter
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()w/namizun/venv/lib/python3.10/site-packages/redis/commands/core.py", line 2220, in set
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)client.py", line 1235, in execute_command
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/connection.py", line 645, in _connect
    for res in socket.getaddrinfo(python3.10/site-packages/redis/connection.py", line 1387, in get_connection
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):.py", line 617, in connect
socket.gaierror: [Errno -2] Name or service not known
redis.exceptions.ConnectionError: Error -2 connecting to localhost:6379. Name or service not known.
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/var/www/namizun/namizun_menu/monitor.py", line 59, in system_usage
    old_bytes_sent, old_bytes_recv = network.get_network_io()
  File "/var/www/namizun/namizun_core/network.py", line 18, in get_network_io
    return io.bytes_sent + database.get_parameter('upload_amount_synchronizer') \
  File "/var/www/namizun/namizun_core/database.py", line 72, in get_parameter
    data = my_db.get(prefix + key)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/commands/core.py", line 1705, in get
    return self.execute_command("GET", name)
  File "/var/www/namizun/venv/lib/python3.10/site-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)

**Comment by AliAzimiD** [comment]
me2
